name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home: /
  About: /1995/03/22/about-me/
  Archives: /archives
  Impressum:
  GitHub:
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
